name: TwitchEventsIntegration
api: TwitchEventsIntegration
main: com.TwitchRewards.Main
version: "1.0.0"
api-version: 1.13
# commands:
#   pos:
#     description: Displays your position or teleports you to another.
#     usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"
#   debug:
#     description: Toggles your debugging status for this plugin.
#     usage: /debug